/**
 * @fileoverview gRPC-Web generated client stub for bpjs
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.21.12
// source: bpjs.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.bpjs = require('./bpjs_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.bpjs.BPJSServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.bpjs.BPJSServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.bpjs.SampleServiceRequest,
 *   !proto.bpjs.SampleServiceResponse>}
 */
const methodDescriptor_BPJSService_SampleService = new grpc.web.MethodDescriptor(
  '/bpjs.BPJSService/SampleService',
  grpc.web.MethodType.UNARY,
  proto.bpjs.SampleServiceRequest,
  proto.bpjs.SampleServiceResponse,
  /**
   * @param {!proto.bpjs.SampleServiceRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.bpjs.SampleServiceResponse.deserializeBinary
);


/**
 * @param {!proto.bpjs.SampleServiceRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.bpjs.SampleServiceResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.bpjs.SampleServiceResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.bpjs.BPJSServiceClient.prototype.sampleService =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/bpjs.BPJSService/SampleService',
      request,
      metadata || {},
      methodDescriptor_BPJSService_SampleService,
      callback);
};


/**
 * @param {!proto.bpjs.SampleServiceRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.bpjs.SampleServiceResponse>}
 *     Promise that resolves to the response
 */
proto.bpjs.BPJSServicePromiseClient.prototype.sampleService =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/bpjs.BPJSService/SampleService',
      request,
      metadata || {},
      methodDescriptor_BPJSService_SampleService);
};


module.exports = proto.bpjs;

