// source: bpjs.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var participant_pb = require('./participant_pb.js');
goog.object.extend(proto, participant_pb);
goog.exportSymbol('proto.bpjs.GetParticipantRequest', null, global);
goog.exportSymbol('proto.bpjs.GetParticipantResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bpjs.GetParticipantRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.bpjs.GetParticipantRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bpjs.GetParticipantRequest.displayName = 'proto.bpjs.GetParticipantRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bpjs.GetParticipantResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.bpjs.GetParticipantResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bpjs.GetParticipantResponse.displayName = 'proto.bpjs.GetParticipantResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bpjs.GetParticipantRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.bpjs.GetParticipantRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bpjs.GetParticipantRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bpjs.GetParticipantRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    servicedate: jspb.Message.getFieldWithDefault(msg, 1, ""),
    bpjsid: jspb.Message.getFieldWithDefault(msg, 2, ""),
    nik: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bpjs.GetParticipantRequest}
 */
proto.bpjs.GetParticipantRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bpjs.GetParticipantRequest;
  return proto.bpjs.GetParticipantRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bpjs.GetParticipantRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bpjs.GetParticipantRequest}
 */
proto.bpjs.GetParticipantRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setServicedate(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setBpjsid(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setNik(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bpjs.GetParticipantRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bpjs.GetParticipantRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bpjs.GetParticipantRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bpjs.GetParticipantRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getServicedate();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getBpjsid();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getNik();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string serviceDate = 1;
 * @return {string}
 */
proto.bpjs.GetParticipantRequest.prototype.getServicedate = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.bpjs.GetParticipantRequest} returns this
 */
proto.bpjs.GetParticipantRequest.prototype.setServicedate = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string bpjsID = 2;
 * @return {string}
 */
proto.bpjs.GetParticipantRequest.prototype.getBpjsid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.bpjs.GetParticipantRequest} returns this
 */
proto.bpjs.GetParticipantRequest.prototype.setBpjsid = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string NIK = 3;
 * @return {string}
 */
proto.bpjs.GetParticipantRequest.prototype.getNik = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.bpjs.GetParticipantRequest} returns this
 */
proto.bpjs.GetParticipantRequest.prototype.setNik = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bpjs.GetParticipantResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.bpjs.GetParticipantResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bpjs.GetParticipantResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bpjs.GetParticipantResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    statusCode: jspb.Message.getFieldWithDefault(msg, 1, 0),
    errorMessage: jspb.Message.getFieldWithDefault(msg, 2, ""),
    message: jspb.Message.getFieldWithDefault(msg, 3, ""),
    participant: (f = msg.getParticipant()) && participant_pb.BPJSParticipant.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bpjs.GetParticipantResponse}
 */
proto.bpjs.GetParticipantResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bpjs.GetParticipantResponse;
  return proto.bpjs.GetParticipantResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bpjs.GetParticipantResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bpjs.GetParticipantResponse}
 */
proto.bpjs.GetParticipantResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setStatusCode(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setErrorMessage(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    case 4:
      var value = new participant_pb.BPJSParticipant;
      reader.readMessage(value,participant_pb.BPJSParticipant.deserializeBinaryFromReader);
      msg.setParticipant(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bpjs.GetParticipantResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bpjs.GetParticipantResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bpjs.GetParticipantResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bpjs.GetParticipantResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStatusCode();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getErrorMessage();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getMessage();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getParticipant();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      participant_pb.BPJSParticipant.serializeBinaryToWriter
    );
  }
};


/**
 * optional int32 status_code = 1;
 * @return {number}
 */
proto.bpjs.GetParticipantResponse.prototype.getStatusCode = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.bpjs.GetParticipantResponse} returns this
 */
proto.bpjs.GetParticipantResponse.prototype.setStatusCode = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string error_message = 2;
 * @return {string}
 */
proto.bpjs.GetParticipantResponse.prototype.getErrorMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.bpjs.GetParticipantResponse} returns this
 */
proto.bpjs.GetParticipantResponse.prototype.setErrorMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string message = 3;
 * @return {string}
 */
proto.bpjs.GetParticipantResponse.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.bpjs.GetParticipantResponse} returns this
 */
proto.bpjs.GetParticipantResponse.prototype.setMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional BPJSParticipant participant = 4;
 * @return {?proto.bpjs.BPJSParticipant}
 */
proto.bpjs.GetParticipantResponse.prototype.getParticipant = function() {
  return /** @type{?proto.bpjs.BPJSParticipant} */ (
    jspb.Message.getWrapperField(this, participant_pb.BPJSParticipant, 4));
};


/**
 * @param {?proto.bpjs.BPJSParticipant|undefined} value
 * @return {!proto.bpjs.GetParticipantResponse} returns this
*/
proto.bpjs.GetParticipantResponse.prototype.setParticipant = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bpjs.GetParticipantResponse} returns this
 */
proto.bpjs.GetParticipantResponse.prototype.clearParticipant = function() {
  return this.setParticipant(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bpjs.GetParticipantResponse.prototype.hasParticipant = function() {
  return jspb.Message.getField(this, 4) != null;
};


goog.object.extend(exports, proto.bpjs);
