// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: bpjs.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SampleServiceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sample string `protobuf:"bytes,1,opt,name=sample,proto3" json:"sample,omitempty"`
}

func (x *SampleServiceRequest) Reset() {
	*x = SampleServiceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bpjs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SampleServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SampleServiceRequest) ProtoMessage() {}

func (x *SampleServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bpjs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SampleServiceRequest.ProtoReflect.Descriptor instead.
func (*SampleServiceRequest) Descriptor() ([]byte, []int) {
	return file_bpjs_proto_rawDescGZIP(), []int{0}
}

func (x *SampleServiceRequest) GetSample() string {
	if x != nil {
		return x.Sample
	}
	return ""
}

type SampleServiceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResponseCode int32         `protobuf:"varint,1,opt,name=response_code,json=responseCode,proto3" json:"response_code,omitempty"`
	Message      string        `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data         *SampleStruct `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SampleServiceResponse) Reset() {
	*x = SampleServiceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bpjs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SampleServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SampleServiceResponse) ProtoMessage() {}

func (x *SampleServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bpjs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SampleServiceResponse.ProtoReflect.Descriptor instead.
func (*SampleServiceResponse) Descriptor() ([]byte, []int) {
	return file_bpjs_proto_rawDescGZIP(), []int{1}
}

func (x *SampleServiceResponse) GetResponseCode() int32 {
	if x != nil {
		return x.ResponseCode
	}
	return 0
}

func (x *SampleServiceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SampleServiceResponse) GetData() *SampleStruct {
	if x != nil {
		return x.Data
	}
	return nil
}

type SampleStruct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age     int32  `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Address string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Phone   string `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
}

func (x *SampleStruct) Reset() {
	*x = SampleStruct{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bpjs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SampleStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SampleStruct) ProtoMessage() {}

func (x *SampleStruct) ProtoReflect() protoreflect.Message {
	mi := &file_bpjs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SampleStruct.ProtoReflect.Descriptor instead.
func (*SampleStruct) Descriptor() ([]byte, []int) {
	return file_bpjs_proto_rawDescGZIP(), []int{2}
}

func (x *SampleStruct) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SampleStruct) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *SampleStruct) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *SampleStruct) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

var File_bpjs_proto protoreflect.FileDescriptor

var file_bpjs_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x62, 0x70, 0x6a, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x62, 0x70,
	0x6a, 0x73, 0x22, 0x2e, 0x0a, 0x14, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x61,
	0x6d, 0x70, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x22, 0x7e, 0x0a, 0x15, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x26, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x62, 0x70, 0x6a, 0x73, 0x2e,
	0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x64, 0x0a, 0x0c, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x53, 0x74, 0x72, 0x75,
	0x63, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x32, 0x59, 0x0a, 0x0b, 0x42, 0x50, 0x4a, 0x53,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4a, 0x0a, 0x0d, 0x53, 0x61, 0x6d, 0x70, 0x6c,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x1a, 0x2e, 0x62, 0x70, 0x6a, 0x73, 0x2e,
	0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x62, 0x70, 0x6a, 0x73, 0x2e, 0x53, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x03, 0x5a, 0x01, 0x2e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bpjs_proto_rawDescOnce sync.Once
	file_bpjs_proto_rawDescData = file_bpjs_proto_rawDesc
)

func file_bpjs_proto_rawDescGZIP() []byte {
	file_bpjs_proto_rawDescOnce.Do(func() {
		file_bpjs_proto_rawDescData = protoimpl.X.CompressGZIP(file_bpjs_proto_rawDescData)
	})
	return file_bpjs_proto_rawDescData
}

var file_bpjs_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_bpjs_proto_goTypes = []interface{}{
	(*SampleServiceRequest)(nil),  // 0: bpjs.SampleServiceRequest
	(*SampleServiceResponse)(nil), // 1: bpjs.SampleServiceResponse
	(*SampleStruct)(nil),          // 2: bpjs.SampleStruct
}
var file_bpjs_proto_depIdxs = []int32{
	2, // 0: bpjs.SampleServiceResponse.data:type_name -> bpjs.SampleStruct
	0, // 1: bpjs.BPJSService.SampleService:input_type -> bpjs.SampleServiceRequest
	1, // 2: bpjs.BPJSService.SampleService:output_type -> bpjs.SampleServiceResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_bpjs_proto_init() }
func file_bpjs_proto_init() {
	if File_bpjs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bpjs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SampleServiceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bpjs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SampleServiceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bpjs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SampleStruct); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bpjs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bpjs_proto_goTypes,
		DependencyIndexes: file_bpjs_proto_depIdxs,
		MessageInfos:      file_bpjs_proto_msgTypes,
	}.Build()
	File_bpjs_proto = out.File
	file_bpjs_proto_rawDesc = nil
	file_bpjs_proto_goTypes = nil
	file_bpjs_proto_depIdxs = nil
}
