// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: reference.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Model definitions for BPJS Reference
type Reference struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *Reference) Reset() {
	*x = Reference{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reference_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reference) ProtoMessage() {}

func (x *Reference) ProtoReflect() protoreflect.Message {
	mi := &file_reference_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reference.ProtoReflect.Descriptor instead.
func (*Reference) Descriptor() ([]byte, []int) {
	return file_reference_proto_rawDescGZIP(), []int{0}
}

func (x *Reference) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Reference) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Reusable Request Template, Empty or Does not need a parameter
type ReferenceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReferenceRequest) Reset() {
	*x = ReferenceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reference_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReferenceRequest) ProtoMessage() {}

func (x *ReferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reference_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReferenceRequest.ProtoReflect.Descriptor instead.
func (*ReferenceRequest) Descriptor() ([]byte, []int) {
	return file_reference_proto_rawDescGZIP(), []int{1}
}

// Reusable Response Template
type ReferenceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode   int32        `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	ErrorMessage string       `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Message      string       `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Reference    []*Reference `protobuf:"bytes,4,rep,name=reference,proto3" json:"reference,omitempty"`
}

func (x *ReferenceResponse) Reset() {
	*x = ReferenceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reference_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReferenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReferenceResponse) ProtoMessage() {}

func (x *ReferenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reference_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReferenceResponse.ProtoReflect.Descriptor instead.
func (*ReferenceResponse) Descriptor() ([]byte, []int) {
	return file_reference_proto_rawDescGZIP(), []int{2}
}

func (x *ReferenceResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ReferenceResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ReferenceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ReferenceResponse) GetReference() []*Reference {
	if x != nil {
		return x.Reference
	}
	return nil
}

type DiagnosisReferenceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DiagnosisCode string `protobuf:"bytes,1,opt,name=diagnosisCode,proto3" json:"diagnosisCode,omitempty"` // ICD-10 Code, Minimal 3 Characters
}

func (x *DiagnosisReferenceRequest) Reset() {
	*x = DiagnosisReferenceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reference_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiagnosisReferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiagnosisReferenceRequest) ProtoMessage() {}

func (x *DiagnosisReferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reference_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiagnosisReferenceRequest.ProtoReflect.Descriptor instead.
func (*DiagnosisReferenceRequest) Descriptor() ([]byte, []int) {
	return file_reference_proto_rawDescGZIP(), []int{3}
}

func (x *DiagnosisReferenceRequest) GetDiagnosisCode() string {
	if x != nil {
		return x.DiagnosisCode
	}
	return ""
}

type DoctorReferenceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceType    string `protobuf:"bytes,1,opt,name=serviceType,proto3" json:"serviceType,omitempty"`
	ServiceDate    string `protobuf:"bytes,2,opt,name=serviceDate,proto3" json:"serviceDate,omitempty"`
	SpecialistCode string `protobuf:"bytes,3,opt,name=specialistCode,proto3" json:"specialistCode,omitempty"`
}

func (x *DoctorReferenceRequest) Reset() {
	*x = DoctorReferenceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reference_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DoctorReferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoctorReferenceRequest) ProtoMessage() {}

func (x *DoctorReferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reference_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoctorReferenceRequest.ProtoReflect.Descriptor instead.
func (*DoctorReferenceRequest) Descriptor() ([]byte, []int) {
	return file_reference_proto_rawDescGZIP(), []int{4}
}

func (x *DoctorReferenceRequest) GetServiceType() string {
	if x != nil {
		return x.ServiceType
	}
	return ""
}

func (x *DoctorReferenceRequest) GetServiceDate() string {
	if x != nil {
		return x.ServiceDate
	}
	return ""
}

func (x *DoctorReferenceRequest) GetSpecialistCode() string {
	if x != nil {
		return x.SpecialistCode
	}
	return ""
}

type PoliclinicsReferenceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PoliCode string `protobuf:"bytes,1,opt,name=poliCode,proto3" json:"poliCode,omitempty"`
	PoliName string `protobuf:"bytes,2,opt,name=poliName,proto3" json:"poliName,omitempty"`
}

func (x *PoliclinicsReferenceRequest) Reset() {
	*x = PoliclinicsReferenceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reference_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PoliclinicsReferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoliclinicsReferenceRequest) ProtoMessage() {}

func (x *PoliclinicsReferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reference_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoliclinicsReferenceRequest.ProtoReflect.Descriptor instead.
func (*PoliclinicsReferenceRequest) Descriptor() ([]byte, []int) {
	return file_reference_proto_rawDescGZIP(), []int{5}
}

func (x *PoliclinicsReferenceRequest) GetPoliCode() string {
	if x != nil {
		return x.PoliCode
	}
	return ""
}

func (x *PoliclinicsReferenceRequest) GetPoliName() string {
	if x != nil {
		return x.PoliName
	}
	return ""
}

type HealthFacilityReferenceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HcName string `protobuf:"bytes,1,opt,name=hcName,proto3" json:"hcName,omitempty"`
	HcType string `protobuf:"bytes,2,opt,name=hcType,proto3" json:"hcType,omitempty"`
}

func (x *HealthFacilityReferenceRequest) Reset() {
	*x = HealthFacilityReferenceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reference_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HealthFacilityReferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthFacilityReferenceRequest) ProtoMessage() {}

func (x *HealthFacilityReferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reference_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthFacilityReferenceRequest.ProtoReflect.Descriptor instead.
func (*HealthFacilityReferenceRequest) Descriptor() ([]byte, []int) {
	return file_reference_proto_rawDescGZIP(), []int{6}
}

func (x *HealthFacilityReferenceRequest) GetHcName() string {
	if x != nil {
		return x.HcName
	}
	return ""
}

func (x *HealthFacilityReferenceRequest) GetHcType() string {
	if x != nil {
		return x.HcType
	}
	return ""
}

type ProcedureReferenceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProcedureCode string `protobuf:"bytes,1,opt,name=procedureCode,proto3" json:"procedureCode,omitempty"` // ICD-9 Code, Minimal 3 Characters
}

func (x *ProcedureReferenceRequest) Reset() {
	*x = ProcedureReferenceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reference_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcedureReferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcedureReferenceRequest) ProtoMessage() {}

func (x *ProcedureReferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reference_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcedureReferenceRequest.ProtoReflect.Descriptor instead.
func (*ProcedureReferenceRequest) Descriptor() ([]byte, []int) {
	return file_reference_proto_rawDescGZIP(), []int{7}
}

func (x *ProcedureReferenceRequest) GetProcedureCode() string {
	if x != nil {
		return x.ProcedureCode
	}
	return ""
}

type RegencyReferenceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProvinceCode string `protobuf:"bytes,1,opt,name=provinceCode,proto3" json:"provinceCode,omitempty"`
}

func (x *RegencyReferenceRequest) Reset() {
	*x = RegencyReferenceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reference_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegencyReferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegencyReferenceRequest) ProtoMessage() {}

func (x *RegencyReferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reference_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegencyReferenceRequest.ProtoReflect.Descriptor instead.
func (*RegencyReferenceRequest) Descriptor() ([]byte, []int) {
	return file_reference_proto_rawDescGZIP(), []int{8}
}

func (x *RegencyReferenceRequest) GetProvinceCode() string {
	if x != nil {
		return x.ProvinceCode
	}
	return ""
}

type DistrictReferenceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RegencyCode string `protobuf:"bytes,1,opt,name=regencyCode,proto3" json:"regencyCode,omitempty"`
}

func (x *DistrictReferenceRequest) Reset() {
	*x = DistrictReferenceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reference_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DistrictReferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistrictReferenceRequest) ProtoMessage() {}

func (x *DistrictReferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reference_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistrictReferenceRequest.ProtoReflect.Descriptor instead.
func (*DistrictReferenceRequest) Descriptor() ([]byte, []int) {
	return file_reference_proto_rawDescGZIP(), []int{9}
}

func (x *DistrictReferenceRequest) GetRegencyCode() string {
	if x != nil {
		return x.RegencyCode
	}
	return ""
}

type AttendingPhysicianReferenceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DoctorCode string `protobuf:"bytes,1,opt,name=doctorCode,proto3" json:"doctorCode,omitempty"`
}

func (x *AttendingPhysicianReferenceRequest) Reset() {
	*x = AttendingPhysicianReferenceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reference_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttendingPhysicianReferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttendingPhysicianReferenceRequest) ProtoMessage() {}

func (x *AttendingPhysicianReferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reference_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttendingPhysicianReferenceRequest.ProtoReflect.Descriptor instead.
func (*AttendingPhysicianReferenceRequest) Descriptor() ([]byte, []int) {
	return file_reference_proto_rawDescGZIP(), []int{10}
}

func (x *AttendingPhysicianReferenceRequest) GetDoctorCode() string {
	if x != nil {
		return x.DoctorCode
	}
	return ""
}

var File_reference_proto protoreflect.FileDescriptor

var file_reference_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x62, 0x70, 0x6a, 0x73, 0x22, 0x33, 0x0a, 0x09, 0x52, 0x65, 0x66, 0x65, 0x72,
	0x65, 0x6e, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x12, 0x0a, 0x10,
	0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0xa2, 0x01, 0x0a, 0x11, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2d, 0x0a, 0x09, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65,
	0x6e, 0x63, 0x65, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x62, 0x70, 0x6a, 0x73,
	0x2e, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x09, 0x72, 0x65, 0x66, 0x65,
	0x72, 0x65, 0x6e, 0x63, 0x65, 0x22, 0x41, 0x0a, 0x19, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73,
	0x69, 0x73, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x69, 0x73, 0x43,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x64, 0x69, 0x61, 0x67, 0x6e,
	0x6f, 0x73, 0x69, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x84, 0x01, 0x0a, 0x16, 0x44, 0x6f, 0x63,
	0x74, 0x6f, 0x72, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x44, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x44, 0x61, 0x74, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x73, 0x70, 0x65, 0x63, 0x69,
	0x61, 0x6c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0e, 0x73, 0x70, 0x65, 0x63, 0x69, 0x61, 0x6c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x22,
	0x55, 0x0a, 0x1b, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x6c, 0x69, 0x6e, 0x69, 0x63, 0x73, 0x52, 0x65,
	0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x6f, 0x6c, 0x69, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x70, 0x6f, 0x6c, 0x69, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f,
	0x6c, 0x69, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6f,
	0x6c, 0x69, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x50, 0x0a, 0x1e, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68,
	0x46, 0x61, 0x63, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x63, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x68, 0x63, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x68, 0x63, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x68, 0x63, 0x54, 0x79, 0x70, 0x65, 0x22, 0x41, 0x0a, 0x19, 0x50, 0x72, 0x6f, 0x63,
	0x65, 0x64, 0x75, 0x72, 0x65, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x64, 0x75,
	0x72, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x70, 0x72,
	0x6f, 0x63, 0x65, 0x64, 0x75, 0x72, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x3d, 0x0a, 0x17, 0x52,
	0x65, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e,
	0x63, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x72,
	0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x3c, 0x0a, 0x18, 0x44, 0x69,
	0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65, 0x67, 0x65, 0x6e, 0x63,
	0x79, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x67,
	0x65, 0x6e, 0x63, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x44, 0x0a, 0x22, 0x41, 0x74, 0x74, 0x65,
	0x6e, 0x64, 0x69, 0x6e, 0x67, 0x50, 0x68, 0x79, 0x73, 0x69, 0x63, 0x69, 0x61, 0x6e, 0x52, 0x65,
	0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e,
	0x0a, 0x0a, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x42, 0x03,
	0x5a, 0x01, 0x2e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_reference_proto_rawDescOnce sync.Once
	file_reference_proto_rawDescData = file_reference_proto_rawDesc
)

func file_reference_proto_rawDescGZIP() []byte {
	file_reference_proto_rawDescOnce.Do(func() {
		file_reference_proto_rawDescData = protoimpl.X.CompressGZIP(file_reference_proto_rawDescData)
	})
	return file_reference_proto_rawDescData
}

var file_reference_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_reference_proto_goTypes = []interface{}{
	(*Reference)(nil),                          // 0: bpjs.Reference
	(*ReferenceRequest)(nil),                   // 1: bpjs.ReferenceRequest
	(*ReferenceResponse)(nil),                  // 2: bpjs.ReferenceResponse
	(*DiagnosisReferenceRequest)(nil),          // 3: bpjs.DiagnosisReferenceRequest
	(*DoctorReferenceRequest)(nil),             // 4: bpjs.DoctorReferenceRequest
	(*PoliclinicsReferenceRequest)(nil),        // 5: bpjs.PoliclinicsReferenceRequest
	(*HealthFacilityReferenceRequest)(nil),     // 6: bpjs.HealthFacilityReferenceRequest
	(*ProcedureReferenceRequest)(nil),          // 7: bpjs.ProcedureReferenceRequest
	(*RegencyReferenceRequest)(nil),            // 8: bpjs.RegencyReferenceRequest
	(*DistrictReferenceRequest)(nil),           // 9: bpjs.DistrictReferenceRequest
	(*AttendingPhysicianReferenceRequest)(nil), // 10: bpjs.AttendingPhysicianReferenceRequest
}
var file_reference_proto_depIdxs = []int32{
	0, // 0: bpjs.ReferenceResponse.reference:type_name -> bpjs.Reference
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_reference_proto_init() }
func file_reference_proto_init() {
	if File_reference_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_reference_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Reference); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reference_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReferenceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reference_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReferenceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reference_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiagnosisReferenceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reference_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DoctorReferenceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reference_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PoliclinicsReferenceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reference_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HealthFacilityReferenceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reference_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcedureReferenceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reference_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegencyReferenceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reference_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DistrictReferenceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reference_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttendingPhysicianReferenceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_reference_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_reference_proto_goTypes,
		DependencyIndexes: file_reference_proto_depIdxs,
		MessageInfos:      file_reference_proto_msgTypes,
	}.Build()
	File_reference_proto = out.File
	file_reference_proto_rawDesc = nil
	file_reference_proto_goTypes = nil
	file_reference_proto_depIdxs = nil
}
