// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: sep.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SEPCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SepJsonStr []byte `protobuf:"bytes,1,opt,name=sepJsonStr,proto3" json:"sepJsonStr,omitempty"`
}

func (x *SEPCreateRequest) Reset() {
	*x = SEPCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sep_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SEPCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SEPCreateRequest) ProtoMessage() {}

func (x *SEPCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sep_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SEPCreateRequest.ProtoReflect.Descriptor instead.
func (*SEPCreateRequest) Descriptor() ([]byte, []int) {
	return file_sep_proto_rawDescGZIP(), []int{0}
}

func (x *SEPCreateRequest) GetSepJsonStr() []byte {
	if x != nil {
		return x.SepJsonStr
	}
	return nil
}

type SEPCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode   int32  `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	BpjsMessage  string `protobuf:"bytes,2,opt,name=bpjsMessage,proto3" json:"bpjsMessage,omitempty"`
	ErrorMessage string `protobuf:"bytes,3,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	Message      string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Sep          string `protobuf:"bytes,5,opt,name=sep,proto3" json:"sep,omitempty"`
}

func (x *SEPCreateResponse) Reset() {
	*x = SEPCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sep_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SEPCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SEPCreateResponse) ProtoMessage() {}

func (x *SEPCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sep_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SEPCreateResponse.ProtoReflect.Descriptor instead.
func (*SEPCreateResponse) Descriptor() ([]byte, []int) {
	return file_sep_proto_rawDescGZIP(), []int{1}
}

func (x *SEPCreateResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *SEPCreateResponse) GetBpjsMessage() string {
	if x != nil {
		return x.BpjsMessage
	}
	return ""
}

func (x *SEPCreateResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *SEPCreateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SEPCreateResponse) GetSep() string {
	if x != nil {
		return x.Sep
	}
	return ""
}

type SEPGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SepNumber string `protobuf:"bytes,1,opt,name=sepNumber,proto3" json:"sepNumber,omitempty"`
}

func (x *SEPGetRequest) Reset() {
	*x = SEPGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sep_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SEPGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SEPGetRequest) ProtoMessage() {}

func (x *SEPGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sep_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SEPGetRequest.ProtoReflect.Descriptor instead.
func (*SEPGetRequest) Descriptor() ([]byte, []int) {
	return file_sep_proto_rawDescGZIP(), []int{2}
}

func (x *SEPGetRequest) GetSepNumber() string {
	if x != nil {
		return x.SepNumber
	}
	return ""
}

type SEPGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode   int32  `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	BpjsMessage  string `protobuf:"bytes,2,opt,name=bpjsMessage,proto3" json:"bpjsMessage,omitempty"`
	ErrorMessage string `protobuf:"bytes,3,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	Message      string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	SepJsonStr   []byte `protobuf:"bytes,5,opt,name=sepJsonStr,proto3" json:"sepJsonStr,omitempty"`
}

func (x *SEPGetResponse) Reset() {
	*x = SEPGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sep_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SEPGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SEPGetResponse) ProtoMessage() {}

func (x *SEPGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sep_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SEPGetResponse.ProtoReflect.Descriptor instead.
func (*SEPGetResponse) Descriptor() ([]byte, []int) {
	return file_sep_proto_rawDescGZIP(), []int{3}
}

func (x *SEPGetResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *SEPGetResponse) GetBpjsMessage() string {
	if x != nil {
		return x.BpjsMessage
	}
	return ""
}

func (x *SEPGetResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *SEPGetResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SEPGetResponse) GetSepJsonStr() []byte {
	if x != nil {
		return x.SepJsonStr
	}
	return nil
}

var File_sep_proto protoreflect.FileDescriptor

var file_sep_proto_rawDesc = []byte{
	0x0a, 0x09, 0x73, 0x65, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x62, 0x70, 0x6a,
	0x73, 0x22, 0x32, 0x0a, 0x10, 0x53, 0x45, 0x50, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x70, 0x4a, 0x73, 0x6f, 0x6e,
	0x53, 0x74, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x73, 0x65, 0x70, 0x4a, 0x73,
	0x6f, 0x6e, 0x53, 0x74, 0x72, 0x22, 0xa5, 0x01, 0x0a, 0x11, 0x53, 0x45, 0x50, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x62,
	0x70, 0x6a, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x62, 0x70, 0x6a, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x22, 0x0a,
	0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73,
	0x65, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x65, 0x70, 0x22, 0x2d, 0x0a,
	0x0d, 0x53, 0x45, 0x50, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x73, 0x65, 0x70, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x73, 0x65, 0x70, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0xb0, 0x01, 0x0a,
	0x0e, 0x53, 0x45, 0x50, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1e, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x20, 0x0a, 0x0b, 0x62, 0x70, 0x6a, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x62, 0x70, 0x6a, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x22, 0x0a, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x70, 0x4a, 0x73, 0x6f, 0x6e, 0x53, 0x74, 0x72, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0a, 0x73, 0x65, 0x70, 0x4a, 0x73, 0x6f, 0x6e, 0x53, 0x74, 0x72, 0x42,
	0x03, 0x5a, 0x01, 0x2e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sep_proto_rawDescOnce sync.Once
	file_sep_proto_rawDescData = file_sep_proto_rawDesc
)

func file_sep_proto_rawDescGZIP() []byte {
	file_sep_proto_rawDescOnce.Do(func() {
		file_sep_proto_rawDescData = protoimpl.X.CompressGZIP(file_sep_proto_rawDescData)
	})
	return file_sep_proto_rawDescData
}

var file_sep_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_sep_proto_goTypes = []interface{}{
	(*SEPCreateRequest)(nil),  // 0: bpjs.SEPCreateRequest
	(*SEPCreateResponse)(nil), // 1: bpjs.SEPCreateResponse
	(*SEPGetRequest)(nil),     // 2: bpjs.SEPGetRequest
	(*SEPGetResponse)(nil),    // 3: bpjs.SEPGetResponse
}
var file_sep_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sep_proto_init() }
func file_sep_proto_init() {
	if File_sep_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sep_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SEPCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sep_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SEPCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sep_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SEPGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sep_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SEPGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sep_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sep_proto_goTypes,
		DependencyIndexes: file_sep_proto_depIdxs,
		MessageInfos:      file_sep_proto_msgTypes,
	}.Build()
	File_sep_proto = out.File
	file_sep_proto_rawDesc = nil
	file_sep_proto_goTypes = nil
	file_sep_proto_depIdxs = nil
}
